[package]
name = "dm-database-parser-sqllog"
version = "0.1.1"
edition = "2024"
authors = ["guangl"]
description = "达梦数据库的 sqllog 日志解析库"
license = "MIT"
repository = "https://github.com/guangl/dm-parser-sqllog"
keywords = ["dm", "sqllog", "parser"]
exclude = [
    "tests"
]


[dependencies]
daachorse = "1.0.0"
once_cell = "1.20"
