[package]
name = "dm-database-parser-sqllog"
version = "0.1.1"
edition = "2024"
authors = ["guangl"]
description = "一个高性能的达梦数据库 sqllog 日志解析库，提供零分配或低分配的记录切分与解析功能"
license = "MIT"
repository = "https://github.com/guangl/dm-parser-sqllog"
documentation = "https://docs.rs/dm-database-parser-sqllog"
homepage = "https://github.com/guangl/dm-parser-sqllog"
keywords = ["dm", "sqllog", "parser", "database", "log", "parsing"]
categories = ["parsing", "database", "text-processing"]
exclude = [
    "tests"
]

[lib]
name = "dm_database_parser_sqllog"
path = "src/lib.rs"

[dependencies]
daachorse = "1.0.0"
once_cell = "1.20"
thiserror = "1.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "parser_bench"
harness = false

[[bench]]
name = "performance_test"
harness = false

[features]
default = []
